#define DEF_ANERO_VERSION_TAG "64a20dead"
#define DEF_ANERO_VERSION "0.1.0.0"
#define DEF_ANERO_RELEASE_NAME "Fluorintine Vermi"
#define DEF_ANERO_VERSION_FULL DEF_ANERO_VERSION "-" DEF_ANERO_VERSION_TAG
#define DEF_ANERO_VERSION_IS_RELEASE false

#include "version.h"

const char* const ANERO_VERSION_TAG = DEF_ANERO_VERSION_TAG;
const char* const ANERO_VERSION = DEF_ANERO_VERSION;
const char* const ANERO_RELEASE_NAME = DEF_ANERO_RELEASE_NAME;
const char* const ANERO_VERSION_FULL = DEF_ANERO_VERSION_FULL;
const bool ANERO_VERSION_IS_RELEASE = DEF_ANERO_VERSION_IS_RELEASE;
