# Fish shell completions for anero-wallet-rpc

complete -c anero-wallet-rpc -f

complete -c anero-wallet-rpc -l help -d "Produce help message"
complete -c anero-wallet-rpc -l version -d "Output version information"
complete -c anero-wallet-rpc -l daemon-address -r -d "Use daemon instance at <host>:<port>"
complete -c anero-wallet-rpc -l daemon-host -r -d "Use daemon instance at host <arg> instead of localhost"
complete -c anero-wallet-rpc -l proxy -r -d "[<ip>:]<port> socks proxy to use for daemon connections"
complete -c anero-wallet-rpc -l trusted-daemon -d "Enable commands which rely on a trusted daemon"
complete -c anero-wallet-rpc -l untrusted-daemon -d "Disable commands which rely on a trusted daemon"
complete -c anero-wallet-rpc -l password -r -d "Wallet password (escape/quote as needed)"
complete -c anero-wallet-rpc -l password-file -r -F -d "Wallet password file"
complete -c anero-wallet-rpc -l daemon-port -r -d "Use daemon instance at port <arg> instead of 61323. Default: 0"
complete -c anero-wallet-rpc -l daemon-login -r -d "Specify username[:password] for daemon RPC client"
complete -c anero-wallet-rpc -l daemon-ssl -x -a "enabled disabled autodetect" -d "Enable SSL on daemon RPC connections. Default: autodetect"
complete -c anero-wallet-rpc -l daemon-ssl-private-key -r -k -a "(__fish_complete_suffix .pem)" -d "Path to a PEM format private key"
complete -c anero-wallet-rpc -l daemon-ssl-certificate -r -k -a "(__fish_complete_suffix .pem)" -d "Path to a PEM format certificate"
complete -c anero-wallet-rpc -l daemon-ssl-ca-certificates -r -F -d "Path to file containing concatenated PEM format certificate(s) to replace system CA(s)."
complete -c anero-wallet-rpc -l daemon-ssl-allowed-fingerprints -r -d "List of valid fingerprints of allowed RPC servers"
complete -c anero-wallet-rpc -l daemon-ssl-allow-any-cert -d "Allow any SSL certificate from the daemon"
complete -c anero-wallet-rpc -l daemon-ssl-allow-chained -d "Allow chain certificates supplied by --daemon-ssl-ca-certificates"
complete -c anero-wallet-rpc -l testnet -d "For testnet. Daemon must also be launched with --testnet flag"
complete -c anero-wallet-rpc -l stagenet -d "For stagenet. Daemon must also be launched with --stagenet flag"
complete -c anero-wallet-rpc -l shared-ringdb-dir -r -F -d "Set shared ring database path"
complete -c anero-wallet-rpc -l kdf-rounds -r -d "Number of rounds for the key derivation function. Default: 1"
complete -c anero-wallet-rpc -l bitmessage-address -r -d "Use PyBitmessage instance at URL <arg>. Default: http://localhost:8442/"
complete -c anero-wallet-rpc -l bitmessage-login -r -d "Specify <arg> as username:password for PyBitmessage API. Default: username:password"
complete -c anero-wallet-rpc -l hw-device -r -d "HW device to use"
complete -c anero-wallet-rpc -l hw-device-deriv-path -r -d "HW device wallet derivation path (e.g., SLIP-10)"
complete -c anero-wallet-rpc -l tx-notify -r -d "Run a program for each new incoming transaction, '%s' replaced by tx hash"
complete -c anero-wallet-rpc -l no-dns -d "Do not use DNS"
complete -c anero-wallet-rpc -l offline -d "Do not connect to a daemon, nor use DNS"
complete -c anero-wallet-rpc -l extra-entropy -r -F -d "File containing extra entropy for PRNG initialization"
complete -c anero-wallet-cli -l allow-mismatched-daemon-version -d "Allow communicating with a daemon using a different version"
complete -c anero-wallet-rpc -l rpc-bind-port -r -d "Sets bind port for server"
complete -c anero-wallet-rpc -l disable-rpc-login -d "Disable HTTP authentication for RPC connections served by this process"
complete -c anero-wallet-rpc -l restricted-rpc -d "Restricts to view-only commands"
complete -c anero-wallet-rpc -l rpc-bind-ip -r -d "Specify IP to bind RPC server. Default: 127.0.0.1"
complete -c anero-wallet-rpc -l rpc-bind-ipv6-address -r -d "Specify IPv6 address to bind RPC server. Default: ::1"
complete -c anero-wallet-rpc -l rpc-restricted-bind-ip -r -d "Specify IP to bind restricted RPC. Default: 127.0.0.1"
complete -c anero-wallet-rpc -l rpc-restricted-bind-ipv6-address -r -d "Specify IPv6 address for restricted RPC. Default: ::1"
complete -c anero-wallet-rpc -l rpc-use-ipv6 -d "Allow IPv6 for RPC"
complete -c anero-wallet-rpc -l rpc-ignore-ipv4 -d "Ignore unsuccessful IPv4 bind for RPC"
complete -c anero-wallet-rpc -l rpc-login -r -d "Specify username[:password] required for RPC server"
complete -c anero-wallet-rpc -l confirm-external-bind -d "Confirm rpc-bind-ip is NOT a loopback (local) IP"
complete -c anero-wallet-rpc -l rpc-access-control-origins -r -d "Comma-separated list of allowed CORS origins"
complete -c anero-wallet-rpc -l rpc-ssl -x -a "enabled disabled autodetect" -d "Enable SSL for RPC. Default: autodetect"
complete -c anero-wallet-rpc -l rpc-ssl-private-key -r -k -a "(__fish_complete_suffix .pem)" -d "Path to PEM private key"
complete -c anero-wallet-rpc -l rpc-ssl-certificate -r -k -a "(__fish_complete_suffix .pem)" -d "Path to PEM certificate"
complete -c anero-wallet-rpc -l rpc-ssl-ca-certificates -r -F -d "Path to PEM CA bundle"
complete -c anero-wallet-rpc -l rpc-ssl-allowed-fingerprints -r -d "List of certificate fingerprints to allow"
complete -c anero-wallet-rpc -l rpc-ssl-allow-chained -d "Allow chained certificates via CA bundle"
complete -c anero-wallet-rpc -l disable-rpc-ban -d "Do not ban hosts on RPC errors"
complete -c anero-wallet-rpc -l wallet-file -r -F -d "Use wallet <arg>"
complete -c anero-wallet-rpc -l generate-from-json -r -k -a "(__fish_complete_suffix .json)" -d "Generate wallet from JSON file"
complete -c anero-wallet-rpc -l wallet-dir -r -F -d "Directory for newly created wallets"
complete -c anero-wallet-rpc -l prompt-for-password -d "Prompt for password when not provided"
complete -c anero-wallet-rpc -l rpc-client-secret-key -r -d "Set RPC client secret key for payment"
complete -c anero-wallet-rpc -l detach -d "Run as daemon"
complete -c anero-wallet-rpc -l pidfile -r -F -d "File path to write daemon PID (requires --detach)"
complete -c anero-wallet-rpc -l non-interactive -d "Run non-interactive"
complete -c anero-wallet-rpc -l log-file -r -F -d "Specify log file"
complete -c anero-wallet-rpc -l log-level -r -a "0 1 2 3 4" -d "0-4 or categories"
complete -c anero-wallet-rpc -l max-log-file-size -r -d "Maximum log file size [B]. Default: 104850000"
complete -c anero-wallet-rpc -l max-log-files -r -d "Max rotated log files to save (0=no limit). Default: 50"
complete -c anero-wallet-rpc -l max-concurrency -d "Max number of threads for parallel jobs. Default: 1"
complete -c anero-wallet-rpc -l config-file -r -F -d "Config file"
