# Fish shell completions for anerod
complete -c anerod -f

complete -c anerod -l help -d "Produce help message"
complete -c anerod -l version -d "Output version information"
complete -c anerod -l config-file -r -d "Specify configuration file"
complete -c anerod -l detach -d "Run as daemon"
complete -c anerod -l pidfile -r -F -d "File path to write the daemon's PID to (optional, requires --detach)"
complete -c anerod -l non-interactive -d "Run non-interactive"
complete -c anerod -l log-file -r -F -d "Specify log file"
complete -c anerod -l log-level -r -d ""
complete -c anerod -l max-log-file-size -r -d "Specify maximum log file size [B]. Default: 104850000"
complete -c anerod -l max-log-files -r -d "Specify maximum number of rotated log files to be saved (no limit by setting to 0). Default: 50"
complete -c anerod -l max-concurrency -r -d "Max number of threads to use for a parallel job. Default: 0"
complete -c anerod -l proxy -r -d "Network communication through proxy: <socks-ip:port>"
complete -c anerod -l proxy-allow-dns-leaks -d "Allow DNS leaks outside of proxy"
complete -c anerod -l public-node -d "Allow others to use this node as remote (restricted RPC mode)"
complete -c anerod -l zmq-rpc-bind-ip -r -d "IP for ZMQ RPC server. Default: 127.0.0.1"
complete -c anerod -l zmq-rpc-bind-port -r -d "Port for ZMQ RPC server. Default: 61324"
complete -c anerod -l zmq-pub -r -d "Address for ZMQ pub - tcp://ip:port or ipc://path"
complete -c anerod -l no-zmq -d "Disable ZMQ RPC server"
complete -c anerod -l data-dir -x -a "(__fish_complete_directories)" -d "Specify data directory"
complete -c anerod -l offline -d "Do not listen/connect to peers"
complete -c anerod -l block-download-max-size -r -d "Set maximum size of block download queue (0 default)"
complete -c anerod -l sync-pruned-blocks -d "Allow syncing from pruned nodes"
complete -c anerod -l max-txpool-weight -r -d "Set maximum txpool weight"
complete -c anerod -l block-notify -r -d "Run a command on new blocks (replaces %s with block hash)"
complete -c anerod -l prune-blockchain -d "Prune blockchain"
complete -c anerod -l p2p-bind-ip -r -d "Interface for p2p protocol (IPv4). Default: 0.0.0.0"
complete -c anerod -l p2p-bind-port -r -d "Port for p2p protocol (IPv4). Default: 54374"
complete -c anerod -l p2p-bind-ipv6-address -r -d "IPv6 interface for p2p protocol"
complete -c anerod -l p2p-use-ipv6 -d "Enable IPv6 for p2p"
complete -c anerod -l p2p-ignore-ipv4 -d "Ignore unsuccessful IPv4 bind"
complete -c anerod -l p2p-external-port -r -d "External port for p2p when NAT/UPnP used"
complete -c anerod -l allow-local-ip -d "Allow local IP in peer list"
complete -c anerod -l add-peer -r -d "Manually add peer to peerlist"
complete -c anerod -l add-priority-node -r -d "Always attempt to stay connected to these nodes"
complete -c anerod -l add-exclusive-node -r -d "Only connect to these nodes"
complete -c anerod -l seed-node -r -d "Connect to node to fetch peers then disconnect"
complete -c anerod -l anonymous-inbound -r -d "Hidden service inbound address"
complete -c anerod -l ban-list -r -F -d "IP ban list file"
complete -c anerod -l hide-my-port -d "Do not advertise peer port"
complete -c anerod -l enable-dns-blocklist -d "Apply realtime DNS blocklist"
complete -c anerod -l no-igd -d "Disable UPnP port mapping"
complete -c anerod -l igd -r -a "Enabled disabled enabled" -d "UPnP port mapping. Default: delayed"
complete -c anerod -l out-peers -r -d "Set max out peers. Default: -1"
complete -c anerod -l in-peers -r -d "Set max inbound peers. Default: -1"
complete -c anerod -l tos-flag -r -d "Set TOS flag"
complete -c anerod -l limit-rate-up -r -d "Limit upload rate [kB/s]. Default: 8192"
complete -c anerod -l limit-rate-down -r -d "Limit download rate [kB/s]. Default: 32768"
complete -c anerod -l limit-rate -r -d "Limit both upload/download [kB/s]"
complete -c anerod -l pad-transactions -d "Pad relayed transactions for metadata protection"
complete -c anerod -l max-connections-per-ip -r -d "Max connections from same IP. Default: 1"

# RPC section

complete -c anerod -l rpc-bind-port -r -d "RPC server port. Default: 61323"
complete -c anerod -l rpc-restricted-bind-port -r -d "Restricted RPC server port"
complete -c anerod -l restricted-rpc -d "Limit RPC to view-only commands"
complete -c anerod -l rpc-bind-ip -r -d "IP to bind RPC server. Default: 127.0.0.1"
complete -c anerod -l rpc-bind-ipv6-address -r -d "IPv6 bind address for RPC"
complete -c anerod -l rpc-use-ipv6 -d "Allow IPv6 for RPC"
complete -c anerod -l rpc-ignore-ipv4 -d "Ignore failed IPv4 RPC binding"
complete -c anerod -l rpc-login -d "Specify username:password for RPC"
complete -c anerod -l confirm-external-bind -d "Confirm RPC bind is not loopback"
complete -c anerod -l rpc-access-control-origins -r -d "Comma separated origins for CORS"
complete -c anerod -l rpc-ssl -x -a "enabled disabled autodetect" -d "Enable SSL for RPC"
complete -c anerod -l rpc-ssl-private-key -r -k -a "(__fish_complete_suffix .pem)" -d "RPC SSL private key"
complete -c anerod -l rpc-ssl-certificate -r -k -a "(__fish_complete_suffix .pem)" -d "RPC SSL certificate"
complete -c anerod -l rpc-ssl-ca-certificates -r -F -d "CA certificates to replace system CA"
complete -c anerod -l rpc-ssl-allowed-fingerprints -r -d "Accepted certificate fingerprints"
complete -c anerod -l rpc-ssl-allow-chained -d "Allow chained certificates via RPC SSL"
complete -c anerod -l disable-rpc-ban -d "Do not ban hosts on RPC errors"
complete -c anerod -l rpc-ssl-allow-any-cert -d "Trust any SSL cert"
complete -c anerod -l rpc-payment-address -r -d "Restrict RPC until micropayment to this address"
complete -c anerod -l rpc-payment-difficulty -r -d "Micropayment difficulty. Default: 1000"
complete -c anerod -l rpc-payment-credits -r -d "Credits granted per payment. Default: 100"
complete -c anerod -l rpc-payment-allow-free-loopback -d "Allow free RPC from localhost"
